parse_config:
  zmk_additional_includes:
    - "modules/zmk/helpers/include"

  zmk_preamble: |
    #include <zmk-helpers/key-labels/eyelash42.h>
    #define CONFIG_WIRELESS

  mark_alternate_layer_activators: true
  sticky_label: $$mdi:gesture-tap-hold$$
  trans_legend:
    tap: $$mdi:transfer$$
    type: trans

  raw_binding_map:
    # System commands
    "&bootloader":
      tap: $$mdi:progress-download$$
      type: bootloader
    "&sys_reset":
      tap: $$mdi:backup-restore$$
      type: bootloader

    # Bluetooth
    "&bt BT_SEL 0":
      hold: "1"
      shifted: $$mdi:bluetooth-connect$$
      tap: BT
    "&bt BT_SEL 1":
      hold: "2"
      shifted: $$mdi:bluetooth-connect$$
      tap: BT
    "&bt BT_SEL 2":
      hold: "3"
      shifted: $$mdi:bluetooth-connect$$
      tap: BT
    "&bt BT_SEL 3":
      hold: "4"
      shifted: $$mdi:bluetooth-connect$$
      tap: BT
    "&bt BT_CLR": $$mdi:bluetooth-off$$

    # Layer management
    "&magic_shift":
      tap: Magic
      hold: $$mdi:apple-keyboard-shift$$
      shifted: $$mdi:alpha-w-box$$
    "&caps_word": $$mdi:alpha-w-box$$

    # Media controls
    "&kp C_MUTE": $$mdi:volume-off$$
    "&kp C_VOL_UP": $$mdi:volume-high$$
    "&kp C_VOL_DN": $$mdi:volume-low$$
    "&kp C_NEXT": $$mdi:skip-next$$
    "&kp C_PREV": $$mdi:skip-previous$$
    "&kp C_PP": $$mdi:play-pause$$

    # Power and brightness
    "&kp C_POWER": $$mdi:power-standby$$
    "&kp C_BRI_UP": $$mdi:brightness-5$$
    "&kp C_BRI_DN": $$mdi:brightness-7$$

    # Special combo keys
    "&dot_spc":
      tap: "."
      shifted: "Sentence"
    "&num_dance":
      tap: "Numword"
      shifted: "Sticky Num"

  zmk_keycode_map:
    # Enhanced modifiers with icons
    LCTRL: $$mdi:apple-keyboard-control$$
    RCTRL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    RALT: $$mdi:apple-keyboard-option$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    LGUI: $$mdi:apple-keyboard-command$$
    RGUI: $$mdi:apple-keyboard-command$$

    # Special modifier combinations
    LS(LC(LALT)): $$mdi:triangle$$  # Meh key

    # Navigation arrows
    UP: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$
    PG_UP: $$mdi:transfer-up$$
    PG_DN: $$mdi:transfer-down$$
    HOME: $$mdi:format-horizontal-align-left$$
    END: $$mdi:format-horizontal-align-right$$

    # Enhanced symbol keys with shift combinations
    MINUS:
      tap: "-"
      shifted: "_"
    EQUAL:
      tap: "="
      shifted: "+"
    SLASH:
      tap: "/"
      shifted: "?"
    BACKSLASH:
      tap: '\'
      shifted: "|"
    SEMICOLON:
      tap: ";"
      shifted: ":"
    SINGLE_QUOTE:
      tap: "'"
      shifted: '"'
    COMMA:
      tap: ","
      shifted: "<"
    DOT:
      tap: "."
      shifted: ">"
    LEFT_BRACKET:
      tap: "["
      shifted: "{"
    RIGHT_BRACKET:
      tap: "]"
      shifted: "}"
    GRAVE:
      tap: "`"
      shifted: "~"

    # Number keys with symbols
    N1:
      tap: "1"
      shifted: "!"
    N2:
      tap: "2"
      shifted: "@"
    N3:
      tap: "3"
      shifted: "#"
    N4:
      tap: "4"
      shifted: "$"
    N5:
      tap: "5"
      shifted: "%"
    N6:
      tap: "6"
      shifted: "^"
    N7:
      tap: "7"
      shifted: "&"
    N8:
      tap: "8"
      shifted: "*"
    N9:
      tap: "9"
      shifted: "("
    N0:
      tap: "0"
      shifted: ")"

    # Special keys with icons
    ENTER:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    SPACE: $$mdi:keyboard-space$$
    BACKSPACE:
      type: backspace
      tap: $$mdi:backspace$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$

    # Locks
    CAPSLOCK: $$mdi:apple-keyboard-caps$$
    CAPS: $$mdi:apple-keyboard-caps$$

    # Media and system
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$
    C_NEXT: $$mdi:skip-next$$
    C_PREV: $$mdi:skip-previous$$
    C_PP: $$mdi:play-pause$$
    C_POWER: $$mdi:power-standby$$
    C_BRI_UP: $$mdi:brightness-5$$
    C_BRI_DN: $$mdi:brightness-7$$

  zmk_combos:
    # Position combos with better alignment
    combo_esc:
      align: top
      offset: 0.1
    combo_tab:
      align: bottom
      offset: 0.1
    combo_enter:
      align: right
      offset: 0.1
    combo_bt_clear:
      align: top
      offset: 0.03

draw_config:
  # Key dimensions
  key_h: 60
  key_rx: 6
  key_ry: 6
  
  # Combo styling
  combo_w: 28
  combo_h: 26
  
  # Spacing
  inner_pad_w: 2
  inner_pad_h: 2
  outer_pad_w: 30
  outer_pad_h: 56
  
  # Text styling
  line_spacing: 1.2
  shrink_wide_legends: 7
  append_colon_to_layer_header: false
  
  # Glyph sizes
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10

  # Clean, modern styling inspired by the example
  svg_style: |
    /* inherit to force styles through use tags */
    svg path {
        fill: inherit;
    }

    /* font and background color specifications */
    svg.keymap {
        /* Color palette */
        --color-bg: #fafafa;
        --color-text: #37474f;
        
        /* Key colors */
        --color-key-bg: #ffffff;
        --color-key-border: #e0e0e0;
        --color-key-text: #37474f;
        --color-key-secondary: #78909c;
        
        /* Layer-specific colors */
        --color-base-bg: #ffffff;
        --color-base-border: #e8eaf6;
        --color-nav-bg: #e8f5e8;
        --color-nav-border: #c8e6c9;
        --color-fn-bg: #fff3e0;
        --color-fn-border: #ffcc80;
        --color-num-bg: #f3e5f5;
        --color-num-border: #ce93d8;
        --color-sys-bg: #ffebee;
        --color-sys-border: #ffcdd2;
        
        /* Modifier keys */
        --color-mod-bg: #e3f2fd;
        --color-mod-border: #bbdefb;
        
        /* Combo colors */
        --color-combo-bg: #f5f5f5;
        --color-combo-border: #e0e0e0;
        --color-combo-text: #616161;
        
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'SF Pro Display', sans-serif;
        font-size: 20px;
        font-weight: 600;
        font-kerning: normal;
        text-rendering: optimizeLegibility;
        background-color: var(--color-bg);
        fill: var(--color-text);
    }

    /* Default key styling */
    rect.key {
      fill: var(--color-key-bg);
      stroke: var(--color-key-border);
      stroke-width: 1;
      shape-rendering: geometricPrecision;
    }

    /* Text positioning and styling */
    text {
        text-anchor: middle;
        dominant-baseline: middle;
        line-height: 1;
    }
    
    .tap {
      fill: var(--color-key-text);
    }
    
    .hold {
      fill: var(--color-key-secondary);
      font-size: 16px;
      text-anchor: middle;
      dominant-baseline: ideographic;
    }
    
    .shifted {
      fill: var(--color-key-secondary);
      font-size: 16px;
      text-anchor: middle;
      dominant-baseline: hanging;
    }

    /* Layer-specific styling */
    .layer-Nav rect.key {
      fill: var(--color-nav-bg);
      stroke: var(--color-nav-border);
    }
    
    .layer-Fn rect.key {
      fill: var(--color-fn-bg);
      stroke: var(--color-fn-border);
    }
    
    .layer-Num rect.key {
      fill: var(--color-num-bg);
      stroke: var(--color-num-border);
    }

    .layer-Sys rect.key,
    .layer-Mouse rect.key {
      fill: var(--color-sys-bg);
      stroke: var(--color-sys-border);
    }

    /* Home row modifier styling */
    .held rect.key {
      fill: var(--color-mod-bg);
      stroke: var(--color-mod-border);
    }

    /* Combo styling */
    rect.combo {
      fill: var(--color-combo-bg);
      stroke: var(--color-combo-border);
      stroke-width: 1;
      opacity: 0.8;
    }
    
    path.combo {
      stroke: var(--color-combo-border);
      stroke-width: 1;
      fill: none;
    }
    
    .combo .tap {
      fill: var(--color-combo-text);
      font-size: 16px;
    }

    .combo .shifted,
    .combo .hold {
      font-size: 13px;
    }

    /* Special key types */
    .trans rect.key {
      opacity: 0.4;
    }
    
    .ghost rect.key {
      opacity: 0.4;
      stroke-dasharray: 2,2;
    }

    /* Layer labels */
    text.label {
      font-size: 36px;
      font-weight: 600;
      fill: var(--color-text);
      text-anchor: start;
      paint-order: stroke;
    }

    /* Glyph styling */
    .glyph {
      opacity: 0.9;
    }

    /* Bootloader and reset keys */
    .bootloader rect.key {
      fill: var(--color-sys-bg);
      stroke: var(--color-sys-border);
    }

    /* Enter and backspace key types */
    .enter rect.key,
    .backspace rect.key {
      fill: var(--color-base-bg);
      stroke: var(--color-base-border);
    }